
config daemon 'daemon'
	option listen "localhost:9999"
	option accept_proxy 0
	option htpasswd /etc/dns/zoneomatic.htpasswd
	# option proxy_header_timeout "10s"
	# option debug 1
	# option otel_endpoint "http://127.0.0.1:4318"
	# option otel_enable_traces 1
	# option otel_traces_endpoint "http://127.0.0.1:4318/v1/traces"
	# option otel_enable_metrics 1
	# option otel_metrics_endpoint "http://127.0.0.1:4318/v1/metrics"
	# option otel_enable_logs 1
	# option otel_logs_endpoint "http://127.0.0.1:4318/v1/logs"
	# option otel_service_name "zoneomatic"
	list zone /etc/dns/example.com.zone
	# list ro_mount '/etc/dns'
	# list rw_mount '/usr/dns'
	# list env 'PATH=/bin'
