config daemon
	option enabled 1
	option central_config /etc/nylon/central.yaml
	option node_config /etc/nylon/node.yaml
	# verbosity and logging
	option verbose 0
	option json_logging 0
	option log_path ''
	# optional extra CLI arguments
