#!/bin/sh

. /lib/functions.sh

INCLUDE_PATH="/usr/share/vpn-sticky/vpn-sticky.include"
FOUND=0

find_vpn_sticky_include() {
	local section="$1"
	local type path

	config_get type "$section" type
	config_get path "$section" path

	[ "$type" = "script" ] || return 0
	[ "$path" = "$INCLUDE_PATH" ] || return 0
	FOUND=1
}

config_load firewall
config_foreach find_vpn_sticky_include include

if [ "$FOUND" -eq 0 ]; then
	uci -q batch <<-EOF
		add firewall include
		set firewall.@include[-1].type='script'
		set firewall.@include[-1].path='$INCLUDE_PATH'
		set firewall.@include[-1].fw4_compatible='1'
		set firewall.@include[-1].enabled='1'
		commit firewall
EOF
fi

rm -f "$0"
