config daemon 'daemon'
	option enabled '0'
	list lan_if 'br-lan'
	# list lan_if 'br-guest'
	# list lan_if 'br-iot'
	option mark_mask '0x70000000'
	list target_prefix '192.168.0.0/16'

config iface 'wg0'
	option name 'wg0'
	option mark '0x10000000'
	option rule_pref '12000'
	option route_table '250'

config iface 'wg1'
	option name 'wg1'
	option mark '0x20000000'
	option rule_pref '12001'
	option route_table '251'

config iface 'wg2'
	option name 'wg2'
	option mark '0x30000000'
	option rule_pref '12002'
	option route_table '252'
