config daemon 'daemon'
	option listen "127.0.0.1:9301"
	option metrics_path "/metrics"
	option squid_hostname "127.0.0.1"
	option squid_port "3128"
	option extract_service_times "1"
	option use_proxy_header "0"
	# option squid_login "user"
	# option squid_password "password"
	# option squid_pidfile "/var/run/squid.pid"
	# list label "instance=router"
	# list ro_mount "/etc/ssl/certs/ca-certificates.crt"
	# list rw_mount "/var/lib/squid"
	# list env "FOO=bar"
	# list extra_arg "--log.level=info"
