#!/bin/sh /etc/rc.common
# shellcheck shell=busybox

USE_PROCD=1
START=99
STOP=1

UC_SCRIPT="/usr/lib/inotify-rsync/inotify-rsync.uc"

extra_command "rsync" "force run rsync scripts"

start_watch() {
	local instance="$1"
	local enabled

	config_get_bool enabled "$instance" enabled 1
	[ "$enabled" = 1 ] || return

	procd_open_instance "$instance"
	procd_set_param command /usr/bin/ucode "$UC_SCRIPT" "$instance"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
}

start_service() {
	local instance="$1"

	config_load inotify-rsync
	if [ -z "$instance" ]; then
		config_foreach start_watch watch
	else
		start_watch "$instance"
	fi
}

start_rsync() {
	local instance="$1"

	/usr/bin/ucode "$UC_SCRIPT" "$instance" sync
}

rsync() {
	local instance="$1"

	config_load inotify-rsync
	if [ -z "$instance" ]; then
		config_foreach start_rsync watch
	else
		start_rsync "$instance"
	fi
}
