config proxmox_backup_server 'pbs_server'
	option enabled '0'
	# see https://pbs.proxmox.com/docs/backup-client.html#environment-variables
	option repository ''
	option password ''
	option fingerprint ''
	option namespace ''
	option backup_name 'rootfs'
	option prefix '/'

	# optional extra proxmox-backup-client backup args (repeatable)
	# list backup_arg '--exclude=/tmp'

	# gotify notification (optional)
	option gotify_url ''
	option gotify_app_token ''
