config daemon 'daemon'
	option enabled "0"
	option config "/etc/pathosd/pathosd.yaml"
	option debug "0"
	option jail "0"
	# enable Linux network namespace for ujail (requires option jail "1")
	option jail_netns "0"
	# list ro_mount "/etc/ssl/certs"
	# list rw_mount "/etc/pathosd"
	# list env "FOO=bar"
	# list extra_arg "--debug"
