#!/bin/sh /etc/rc.common

START=80
USE_PROCD=1

PROG=/usr/bin/netobserv-ebpf-agent
CONF=netobserv-ebpf-agent

iface_append() {
	[ -n "$interfaces" ] && interfaces="$interfaces,"
	interfaces="$interfaces$1"
}

start_service() {
	local enabled export target_host target_port interfaces
	local exclude direction active_timeout log_level

	config_load "$CONF"
	config_get_bool enabled service enabled 0
	[ "$enabled" -ne 0 ] || return

	config_get export        service export ipfix+udp
	config_get target_host   service target_host 127.0.0.1
	config_get target_port   service target_port 4739
	config_get exclude       service exclude_interfaces lo
	config_get direction     service direction both
	config_get active_timeout service cache_active_timeout 5s
	config_get log_level     service log_level info

	interfaces=""
	config_list_foreach service interfaces iface_append

	procd_open_instance
	procd_set_param command "$PROG"

	procd_set_param env \
		EXPORT="$export" \
		TARGET_HOST="$target_host" \
		TARGET_PORT="$target_port" \
		EXCLUDE_INTERFACES="$exclude" \
		DIRECTION="$direction" \
		CACHE_ACTIVE_TIMEOUT="$active_timeout" \
		LOG_LEVEL="$log_level"
	[ -n "$interfaces" ] && procd_append_param env INTERFACES="$interfaces"

	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "$CONF"
}
