config daemon 'daemon'
	option jail "1"
	option listen "127.0.0.1:9167"
	option metrics_path "/metrics"
	option unbound_host "tcp://127.0.0.1:8953"
	option unbound_ca ""
	option unbound_cert ""
	option unbound_key ""
	# option unbound_host "unix:///var/run/unbound.ctl"
	# option unbound_ca "/var/lib/unbound/unbound_server.pem"
	# option unbound_cert "/var/lib/unbound/unbound_control.pem"
	# option unbound_key "/var/lib/unbound/unbound_control.key"
	# list ro_mount "/etc/ssl/certs/ca-certificates.crt"
	# list rw_mount "/var/lib/unbound"
	# list env "FOO=bar"
	# list extra_arg "--some.flag=value"
