mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:
  - name: direct
    type: direct

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - direct

rules:
  - MATCH,PROXY