config daemon 'daemon'
	option enabled '0'
	option user 'mihomo'
	option config '/etc/mihomo/config.yaml'
	option workdir '/usr/share/mihomo'
	option jail '1'
#	list ro_mount '/etc/ssl/certs'
#	list ro_mount '/etc/localtime'
#	list rw_mount '/var/log/mihomo'
#	list extra_arg '-v'