#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99

script=$(readlink "$initscript")
NAME="$(basename ${script:-$initscript})"
PROG="/usr/bin/mihomo"

start_service() {
	config_load "$NAME"

	local enabled user config workdir jail ro_mount rw_mount
	config_get_bool enabled "main" "enabled" "0"
	[ "$enabled" -eq "1" ] || return 0

	config_get user "main" "user" "mihomo"
	config_get config "main" "config" "/etc/mihomo/config.yaml"
	config_get workdir "main" "workdir" "/usr/share/mihomo"
	config_get_bool jail "main" "jail" "1"
	config_get ro_mount "main" "ro_mount"
	config_get rw_mount "main" "rw_mount"

	mkdir -p "$workdir"
	local group="$(id -ng $user)"
	chown $user:$group "$workdir"

	procd_open_instance "$NAME.main"
	procd_set_param command "$PROG" -f "$config" -d "$workdir"

	# Use root user if you want to use the TUN mode.
	procd_set_param user "$user"
	procd_set_param file "$config"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn

	if [ "$jail" -eq "1" ]; then
		procd_add_jail "$NAME.main" log requirejail
		procd_add_jail_mount "$config"
		procd_add_jail_mount_rw "$workdir"
		for path in $ro_mount; do
			procd_add_jail_mount "$path"
		done
		for path in $rw_mount; do
			procd_add_jail_mount_rw "$path"
		done
	fi

	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "$NAME"
}