#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

PROG=/usr/bin/mihomo
CONF=mihomo

list_append_args() {
	procd_append_param command "$1"
}

start_service() {
	local enabled user config workdir jail

	config_load "$CONF"
	config_get_bool enabled daemon enabled 0
	[ "$enabled" -ne 0 ] || return 0

	config_get user daemon user "mihomo"
	config_get config daemon config "/etc/mihomo/config.yaml"
	config_get workdir daemon workdir "/usr/share/mihomo"
	config_get_bool jail daemon jail 1

	mkdir -p "$workdir"
	local group="$(id -ng $user)"
	chown $user:$group "$workdir"

	procd_open_instance

	procd_set_param command "$PROG" -f "$config" -d "$workdir"

	# Use root user if you want to use the TUN mode.
	procd_set_param user "$user"
	procd_set_param file "$config"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn

	if [ "$jail" -ne 0 ]; then
		procd_add_jail mihomo log requirejail
		procd_add_jail_mount "$config"
		procd_add_jail_mount_rw "$workdir"
		config_list_foreach daemon ro_mount procd_add_jail_mount
		config_list_foreach daemon rw_mount procd_add_jail_mount_rw
	fi

	config_list_foreach daemon extra_arg list_append_args

	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "$CONF"
}