#!/bin/sh /etc/rc.common

# shellcheck shell=dash
USE_PROCD=1
START=99

PROG=/usr/bin/mihomo
CONF=mihomo

list_append_args() {
	procd_append_param command "$1"
}

start_instance() {
	local enabled user config workdir jail

	config_get_bool enabled "$1" enabled 0
	[ "$enabled" -ne 0 ] || return 0

	config_get config "$1" config "/etc/mihomo/config.yaml"
	config_get workdir "$1" workdir "/var/lib/mihomo"
	config_get_bool jail "$1" jail 1
	config_get user "$1" user "mihomo"

	local group="$(id -ng $user)"
	mkdir -p "$workdir"
	chown "$user:$group" "$workdir"

	procd_open_instance "$1"

	procd_set_param command "$PROG" -f "$config" -d "$workdir"
	config_list_foreach "$1" extra_arg list_append_args

	# Use root user if you want to use the TUN mode.
	procd_set_param user "$user"
	procd_set_param file "$config"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param reload_signal HUP
	procd_set_param respawn
	procd_set_param limits core="unlimited"
	procd_set_param limits nofile="1000000 1000000"

	if [ "$jail" -ne 0 ]; then
		procd_add_jail mihomo log
		procd_add_jail_mount "$config"
		procd_add_jail_mount_rw "$workdir"
		config_list_foreach "$1" ro_mount procd_add_jail_mount
		config_list_foreach "$1" rw_mount procd_add_jail_mount_rw
		[ -x /sbin/ujail -a -e /etc/capabilities/mihomo.json ] && \
			procd_set_param capabilities /etc/capabilities/mihomo.json
	fi

	procd_close_instance
}

start_service() {
	config_load "$CONF"
	config_foreach start_instance instance
}

service_triggers() {
	procd_add_reload_trigger "$CONF"
}
