include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for dummy interfaces
LUCI_DESCRIPTION:=LuCI form for the netifd dummy-interface protocol
LUCI_DEPENDS:=+luci-base +netifd-proto-dummy
LUCI_PKGARCH:=all

PKG_LICENSE:=GPL-2.0-only
PKG_MAINTAINER:=Vladimir Ermakov <vooon341@gmail.com>

include $(TOPDIR)/feeds/luci/luci.mk