
config rsync_sysupgrade 'settings'
	option enabled '0'
	# rsync source URL, e.g. rsync://owrt-fw/images/
	option rsync_url ''
	# profile name matching releases/<tag>/<profile>/ directory, e.g. 'cr', 'pf-i5'
	option profile ''
	# firmware filename inside the profile directory, e.g. openwrt-cr-x86-64-generic-squashfs-combined-efi.img.gz
	option filename ''
	# extra rsync args
	option rsync_args '-P'
	# extra sysupgrade args, passed directly to sysupgrade (e.g. '-u' to skip unchanged files matching /rom)
	option sysupgrade_args '-u'
